/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventarioropa;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author NATANAEL MORENO
 */
public class Principal extends javax.swing.JFrame {

    ResultSet rs = null;

    DefaultComboBoxModel modeloarticulo = new DefaultComboBoxModel();
    DefaultComboBoxModel modelomaterial = new DefaultComboBoxModel();
    DefaultComboBoxModel modelomarca = new DefaultComboBoxModel();
    DefaultComboBoxModel modelotalla = new DefaultComboBoxModel();
    DefaultComboBoxModel modelopais = new DefaultComboBoxModel();

    metodosdos articulo = new metodosdos();
    metodosdos material = new metodosdos();
    metodosdos marca = new metodosdos();
    metodosdos talla = new metodosdos();
   metodosdos pais = new metodosdos();

    /**
     * Creates new form Principal
     */
    metodos llamar = new metodos();
    boolean encontrado = false;
    
    public Principal() {
        initComponents();
         this.setLocationRelativeTo(rootPane);

        setTitle(" YAEL");

        // llenado de combobox articulos
        rs = articulo.llenarArticulos();
        modeloarticulo.addElement("seleccione");
        try {
            while (rs.next()) {
                modeloarticulo.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        //cmbarticulo.setModel(modeloarticulo);

        // llenado de combobox materiales
        rs = material.llenarMateriales();
        modelomaterial.addElement("seleccione");
        try {
            while (rs.next()) {
                modelomaterial.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        cmbmaterial.setModel(modelomaterial);

        // llenado de combobox marcas
        rs = marca.llenarMarcas();
        modelomarca.addElement("seleccione");
        try {
            while (rs.next()) {
                modelomarca.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        cmbmarca.setModel(modelomarca);

        // llenado de combobox tallas
        rs = talla.llenarTallas();
        modelotalla.addElement("seleccione");
        try {
            while (rs.next()) {
                modelotalla.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        cmbtalla.setModel(modelotalla);

        // llenado de combobox pais 
        rs = pais.llenarPaises();
        modelopais.addElement("seleccione");
        try {
            while (rs.next()) {
                modelopais.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        cmbpais.setModel(modelopais);
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtexistencia = new javax.swing.JTextField();
        txtarticulo = new javax.swing.JTextField();
        cmbtalla = new javax.swing.JComboBox<>();
        cmbmarca = new javax.swing.JComboBox<>();
        cmbmaterial = new javax.swing.JComboBox<>();
        cmbpais = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGModificar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PicsArt_06-20-11.03.25.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(108, 269));
        jLabel1.setRequestFocusEnabled(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 900, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setText("Codigo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("Existencia");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setText("Articulo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText("Talla");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("Marca");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setText("Material");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setText("Pais");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 166, -1));
        jPanel1.add(txtexistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 166, -1));
        jPanel1.add(txtarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 166, -1));

        jPanel1.add(cmbtalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 166, -1));

        jPanel1.add(cmbmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 166, -1));

        jPanel1.add(cmbmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 166, -1));

        jPanel1.add(cmbpais, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 166, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/new.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 130, 50));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 130, 50));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 130, 50));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 130, 50));

        btnGModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardarCambios.png"))); // NOI18N
        btnGModificar.setText("Guardar Modificacion");
        btnGModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/_disabled__document.png"))); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 130, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit.png"))); // NOI18N
        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 130, 50));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 153, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bb60c392163c2bb12fd52bec3af0d5e6.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 640, 490));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 40, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
          txtarticulo.setText("");
        cmbmaterial.setSelectedIndex(0);
        cmbmarca.setSelectedIndex(0);
        cmbtalla.setSelectedIndex(0);
        cmbpais.setSelectedIndex(0); 

        desbloquear();
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
          if (this.txtarticulo.getText() == null) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un articulo", "AVISO DEL SISTEMA", 2);

        } else if (this.cmbmaterial.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un material", "AVISO DEL SISTEMA", 2);

        } else if (this.cmbmarca.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una marca", "AVISO DEL SISTEMA", 2);

        } else if (this.cmbtalla.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una talla", "AVISO DEL SISTEMA", 2);

        } else if (this.cmbpais.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un pais", "AVISO DEL SISTEMA", 2);

        } else {
            llamar.insertar7(this.txtcodigo.getText(),this.txtarticulo.getText(), this.cmbmaterial.getSelectedIndex(), this.cmbmarca.getSelectedIndex(), this.cmbtalla.getSelectedIndex(), this.cmbpais.getSelectedIndex(), Integer.parseInt(this.txtexistencia.getText()));
            JOptionPane.showMessageDialog(null,"ingreso exitoso");
               limpiar();
    }        
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         String codigo = JOptionPane.showInputDialog("Ingrese el código del articulo a búscar:");
        if (codigo != null) {
            rs = llamar.buscar7(codigo);
        } 

        encontrado = false;

        try {
            
            while (rs.next()) {
                this.txtcodigo.setText(rs.getString(1));
                
                this.txtarticulo.setText(rs.getString(2));
                this.cmbmarca.setSelectedIndex(rs.getInt(3));
                this.cmbtalla.setSelectedIndex(rs.getInt(4));
                this.cmbpais.setSelectedIndex(rs.getInt(5));
                 this.cmbmaterial.setSelectedIndex(rs.getInt(6));
                this.txtexistencia.setText(rs.getString(7));
                
                encontrado = true;
                JOptionPane.showMessageDialog(null, "encontrado");

                txtarticulo.setEnabled(false);
                cmbmaterial.setEnabled(false);
                cmbmarca.setEnabled(false);
                cmbtalla.setEnabled(false);
                cmbpais.setEnabled(false);
                  txtexistencia.setEnabled(false);
            }
            if (encontrado == false) {
                JOptionPane.showMessageDialog(rootPane, "Registro no encontrado!!!", "AVISO DEL SISTEMA", 0);
               
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (encontrado == true) {
            desbloquear();

        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGModificarActionPerformed
          llamar.modificar7(this.txtcodigo.getText(), this.txtarticulo.getText(),this.cmbmarca.getSelectedIndex(), this.cmbtalla.getSelectedIndex() , this.cmbpais.getSelectedIndex(),this.cmbmaterial.getSelectedIndex(),  Integer.parseInt(this.txtexistencia.getText()));
        JOptionPane.showMessageDialog(rootPane, "Registro modificado con éxito.", "AVISO DEL SISTEMA", 1);
    }//GEN-LAST:event_btnGModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
       frmtabla ropa=new frmtabla();
    ropa.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnMostrarActionPerformed
 public void limpiar() {
        txtcodigo.setText("");
        txtexistencia.setText("");
        txtarticulo.setText("");
         cmbmaterial.setSelectedIndex(0);
        cmbmarca.setSelectedIndex(0);
        cmbtalla.setSelectedIndex(0);
        cmbpais.setSelectedIndex(0); 
    }

    public void desbloquear() {
        txtcodigo.setEnabled(true);
        txtarticulo.setEnabled(true);
        txtexistencia.setEnabled(true);
        cmbmaterial.setEnabled(true);
        cmbmarca.setEnabled(true);
        cmbtalla.setEnabled(true);
        cmbpais.setEnabled(true);

    }

    public void bloquear() {
        txtcodigo.setEnabled(false);
        txtarticulo.setEnabled(false);
        txtexistencia.setEnabled(false);
        cmbmaterial.setEnabled(false);
        cmbmarca.setEnabled(false);
        cmbtalla.setEnabled(false);
        cmbpais.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGModificar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JComboBox<String> cmbmaterial;
    private javax.swing.JComboBox<String> cmbpais;
    private javax.swing.JComboBox<String> cmbtalla;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtarticulo;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtexistencia;
    // End of variables declaration//GEN-END:variables
}
